In [2]:
#Data Generation
import numpy as np
import matplotlib.pyplot as plt
m = 100
X = 6 * np.random.randn(m, 1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)
degree = 2

In [3]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha = 1, solver = 'cholesky')
ridge_reg.fit(X, y)
ridge_reg.predict([[1.5]])

array([[6.61856556]])

In [4]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(penalty = 'l2')
sgd_reg.fit(X, y.ravel())
sgd_reg.predict([[1.5]])

array([4.86320558])

In [5]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha = 0.1)
lasso_reg.fit(X, y)
lasso_reg.predict([[1.5]])

array([6.62939513])

In [3]:
from sklearn.linear_model import ElasticNet
elasticnet = ElasticNet(alpha = 0.1, l1_ratio = 0.5)
elasticnet.fit(X, y)
elasticnet.predict([[1.5]])

NameError: name 'X' is not defined